spring:
  profiles:
    active:
      - sql
#      - json
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:mysql://78.46.187.170:3306/lardi?useUnicode=yes&characterEncoding=UTF-8
    username: lardi
    password: lardi

  devtools:
    restart:
      enabled: true
      
lardi:
  contact:
    limit: 3
  storage:
    path: C:\Temp\lardi-json